"""create all tables

Revision ID: 2ce26130b610
Revises: 046895af551b
Create Date: 2026-01-12 11:09:40.798178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce26130b610'
down_revision: Union[str, Sequence[str], None] = '046895af551b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'support_messages', 'contact_messages', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_messages', type_='foreignkey')
    op.drop_column('support_messages', 'contact_id')
    # ### end Alembic commands ###
