"""create all tables

Revision ID: 7f6123e1665f
Revises: 2ce26130b610
Create Date: 2026-01-28 23:22:02.745454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6123e1665f'
down_revision: Union[str, Sequence[str], None] = '2ce26130b610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('tag', sa.Enum('featured', 'on_sale', 'top_rated', name='promotype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promos', 'tag')
    # ### end Alembic commands ###
