"""create all tables

Revision ID: f8cc3579e2b8
Revises: c52368db2dbc
Create Date: 2025-12-03 13:05:47.110821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cc3579e2b8'
down_revision: Union[str, Sequence[str], None] = 'c52368db2dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compare_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'product_id', name='unique_compare_product_per_device')
    )
    op.create_index(op.f('ix_compare_items_device_id'), 'compare_items', ['device_id'], unique=False)
    op.create_index(op.f('ix_compare_items_id'), 'compare_items', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'product_id', name='unique_favorite_product_per_device')
    )
    op.create_index(op.f('ix_favorites_device_id'), 'favorites', ['device_id'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('recent_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_views_device_id'), 'recent_views', ['device_id'], unique=False)
    op.create_index(op.f('ix_recent_views_id'), 'recent_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recent_views_id'), table_name='recent_views')
    op.drop_index(op.f('ix_recent_views_device_id'), table_name='recent_views')
    op.drop_table('recent_views')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_device_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_compare_items_id'), table_name='compare_items')
    op.drop_index(op.f('ix_compare_items_device_id'), table_name='compare_items')
    op.drop_table('compare_items')
    # ### end Alembic commands ###
